#' simBitesLogit: Generates a bite dataset by randomly sampling time
#'
#' This function generates a bite dataset from meal duration, number of bites, and total intake (Emax) by randomly sampling a logistic distrubtion truncated to only include positive values
#'
#' @param mealdur Meal duration in minutes
#' @inheritParams simBites
#' @inheritParams simBites
#' @param id (optional) ID number, if exists will be added to output_dat. Default is no id.
#' @inheritParams simBites
#'
#'
#' @return A bite dataset generated by randomly sampling time
#'
#' @examples
#'
#' \dontrun{
#' }
#'
#'
#' @export

simBitesLogit = function(mealdur, nBites, Emax, id){

  #get randomly generated values from logistic distribution
  randlogistic = sort(rtrunc(rlogis, nBites, 0))
  rand_time = (randlogistic/max(randlogistic))*mealdur
  sampled_time = jitter(rand_time, factor = 2)

  #make sure starting value is 0 or greater for first bite
  if(sampled_time[1]<0){
    sampled_time[1] = 0
  }

  #make sure the jitter didn't extend the meal duraiton
  if(sampled_time[nBites] > mealdur){
    sampled_time[nBites] = mealdur
  }

  #get bite numbers
  bites = seq(1, nBites, by = 1)

  #get cummulative intake
  grams.bite_avg = rep(Emax/nBites, nBites)
  grams.cumulative_avg = cumsum(grams.bite_avg)

  if(hasArg(id)){
    sim_dat = data.frame(rep(id, length(nBites)), bites, sampled_time, grams.cumulative_avg)
    names(sim_dat) = c('id', 'Bite', 'Time', 'CumulativeGrams_avgBite')
  } else {
    sim_dat = data.frame(bites, sampled_time, grams.cumulative_avg)
    names(sim_dat) = c('Bite', 'Time', 'CumulativeGrams_avgBite')
  }

  #set up output_dat
  return(sim_dat)
}
